language: elixir

elixir:
  - 1.9.4

otp_release:
  - 22.0

script:
  - mix format --check-formatted
  - mix compile --warnings-as-errors
  - mix test
  - travis_wait 30 mix dialyzer
  - mix credo --strict

cache:
  directories:
    - priv/plts

sudo: false
