language: elixir

elixir:
  - 1.9

otp_release:
  - 22.0

script:
  - mix format --check-formatted
  - mix test
  - mix dialyzer
  - mix credo --strict

cache:
  directories:
    - priv/plts

sudo: false
